// <<< EDITOR:STYLE START >>>
export const DEFAULT_STYLE = {
  version: 1,
  preset: 'editorial',
  layout: {
    landing: 'minimal',
  },
  design: {
    spacing: 0.5,
    alignment: 'editorial',
    hierarchy: 0.62,
    contrast: 0.66,
    proportion: 0.5,
  },
  color: {
    background: '#ebe2c8',
    surface: '#e0d6ba',
    text: '#1a1814',
    muted: '#5e574b',
    primary: '#3a7a82',
    secondary: '#b8924a',
    contrast: 0.72,
    saturation: 0.55,
    temperature: 0.1,
  },
  typography: {
    personality: 'editorial',
    display: 'serif',
    body: 'sans',
    scale: 1.333,
    tracking: 0,
  },
  space: {
    density: 0.45,
    radius: 6,
    sectionGap: 96,
    cardGap: 20,
  },
  motion: {
    mode: 'lively',
    duration: 280,
    easing: 'easeOut',
    motif: 'film',
    scrollIntensity: 0.4,
    ambient: true,
    interaction: 'subtle',
  },
  texture: {
    grain: 0.09,
    imageSaturation: 1,
    imageContrast: 1,
    imageBrightness: 1,
  },
  light: {
    shadowDepth: 0.28,
    shadowSoftness: 0.58,
    highlight: 0.18,
  },
  culture: {
    era: 'contemporary',
    register: 'hybrid',
    medium: 'digital',
  },
  depth: {
    blur: 0,
    glass: 0.08,
    parallax: 0.12,
  },
  mood: ['editorial', 'quiet', 'warm'],
  anchors: [
    {
      id: 'anchor-editorial-paper',
      type: 'note',
      title: 'Warm paper portfolio',
      url: '',
      note: 'Soft paper surfaces, restrained serif hierarchy, teal and ochre accents.',
      weight: 0.65,
    },
  ],
}
// <<< EDITOR:STYLE END >>>

export const STYLE_DIMENSIONS = [
  {
    key: 'design',
    label: { zh: '设计基础', en: 'Design' },
    summary: 'spacing, alignment, hierarchy, contrast, proportion',
  },
  { key: 'color', label: { zh: '色彩', en: 'Color' }, summary: 'palette, contrast, saturation' },
  {
    key: 'typography',
    label: { zh: '排版', en: 'Type' },
    summary: 'font personality, scale, tracking',
  },
  { key: 'space', label: { zh: '空间', en: 'Space' }, summary: 'density, radius, rhythm' },
  {
    key: 'motion',
    label: { zh: '动态', en: 'Motion' },
    summary: 'tempo, motif, scroll response, interaction',
  },
  {
    key: 'texture',
    label: { zh: '质感', en: 'Texture' },
    summary: 'grain overlay, image filter, surface feel',
  },
  {
    key: 'light',
    label: { zh: '光影', en: 'Light' },
    summary: 'shadow, softness, highlight language',
  },
  {
    key: 'culture',
    label: { zh: '语境', en: 'Culture' },
    summary: 'descriptive era / medium references — part of the mood board, not a live control',
  },
  { key: 'depth', label: { zh: '深度', en: 'Depth' }, summary: 'blur, glass, parallax depth' },
]

export const STYLE_MOOD_KEYWORDS = [
  { value: 'editorial', label: { zh: '编辑感', en: 'Editorial' } },
  { value: 'quiet', label: { zh: '安静', en: 'Quiet' } },
  { value: 'warm', label: { zh: '温暖', en: 'Warm' } },
  { value: 'personal', label: { zh: '私人', en: 'Personal' } },
  { value: 'minimal', label: { zh: '克制', en: 'Minimal' } },
  { value: 'cinematic', label: { zh: '电影感', en: 'Cinematic' } },
  { value: 'literary', label: { zh: '文学性', en: 'Literary' } },
  { value: 'moody', label: { zh: '低照度', en: 'Moody' } },
  { value: 'digital', label: { zh: '数码感', en: 'Digital' } },
  { value: 'playful', label: { zh: '玩心', en: 'Playful' } },
  { value: 'organic', label: { zh: '自然', en: 'Organic' } },
  { value: 'sharp', label: { zh: '锋利', en: 'Sharp' } },
  { value: 'handmade', label: { zh: '手作', en: 'Handmade' } },
  { value: 'grainy', label: { zh: '颗粒', en: 'Grainy' } },
  { value: 'earthy', label: { zh: '土壤感', en: 'Earthy' } },
  { value: 'cold', label: { zh: '冷感', en: 'Cold' } },
  { value: 'deep', label: { zh: '深沉', en: 'Deep' } },
]

export const STYLE_ANCHOR_TYPES = [
  { value: 'image', label: { zh: '图片', en: 'Image' } },
  { value: 'film', label: { zh: '电影', en: 'Film' } },
  { value: 'site', label: { zh: '网站', en: 'Website' } },
  { value: 'object', label: { zh: '物件', en: 'Object' } },
  { value: 'note', label: { zh: '文字', en: 'Note' } },
]

export const STYLE_PRESETS = {
  editorial: {
    label: { zh: '编辑室', en: 'Editorial' },
    description: { zh: '纸感、克制、适合个人作品集', en: 'paper-like, quiet, portfolio-ready' },
    style: DEFAULT_STYLE,
  },
  ink: {
    label: { zh: '水墨', en: 'Ink wash' },
    description: { zh: '低饱和、留白、墨色层次', en: 'muted, spacious, ink-toned' },
    style: {
      ...DEFAULT_STYLE,
      preset: 'ink',
      color: {
        ...DEFAULT_STYLE.color,
        background: '#f1eee4',
        surface: '#e5dfcf',
        text: '#151514',
        muted: '#68655d',
        primary: '#2f4f4f',
        secondary: '#89795c',
        saturation: 0.28,
        temperature: -0.05,
      },
      design: {
        ...DEFAULT_STYLE.design,
        spacing: 0.72,
        alignment: 'editorial',
        hierarchy: 0.48,
        contrast: 0.46,
        proportion: 0.42,
      },
      typography: {
        ...DEFAULT_STYLE.typography,
        personality: 'quiet',
        display: 'serif',
        body: 'serif',
        tracking: 6,
      },
      space: { ...DEFAULT_STYLE.space, density: 0.32, radius: 3, sectionGap: 112 },
      motion: {
        ...DEFAULT_STYLE.motion,
        mode: 'calm',
        duration: 420,
        easing: 'easeInOut',
        motif: 'botanical',
        scrollIntensity: 0.22,
      },
      texture: {
        ...DEFAULT_STYLE.texture,
        grain: 0.11,
        imageSaturation: 0.82,
        imageContrast: 0.96,
        imageBrightness: 1.02,
      },
      light: { ...DEFAULT_STYLE.light, shadowDepth: 0.14, shadowSoftness: 0.72, highlight: 0.08 },
      depth: { ...DEFAULT_STYLE.depth, glass: 0.03, parallax: 0.08 },
      mood: ['quiet', 'minimal', 'organic'],
      anchors: [
        {
          id: 'anchor-ink-wash',
          type: 'note',
          title: 'Ink wash negative space',
          url: '',
          note: 'Low saturation, generous blank space, soft ink borders.',
          weight: 0.72,
        },
      ],
    },
  },
  coldModern: {
    label: { zh: '冷峻', en: 'Cold modern' },
    description: { zh: '清晰、结构化、低温科技感', en: 'crisp, structured, cool' },
    style: {
      ...DEFAULT_STYLE,
      preset: 'coldModern',
      color: {
        ...DEFAULT_STYLE.color,
        background: '#eef2f4',
        surface: '#dde6ea',
        text: '#101519',
        muted: '#52616b',
        primary: '#2563eb',
        secondary: '#0f766e',
        contrast: 0.82,
        saturation: 0.5,
        temperature: -0.45,
      },
      design: {
        ...DEFAULT_STYLE.design,
        spacing: 0.42,
        alignment: 'grid',
        hierarchy: 0.62,
        contrast: 0.78,
        proportion: 0.58,
      },
      typography: {
        ...DEFAULT_STYLE.typography,
        personality: 'modern',
        display: 'sans',
        body: 'sans',
        tracking: 2,
      },
      space: { ...DEFAULT_STYLE.space, density: 0.5, radius: 2, sectionGap: 88 },
      motion: {
        ...DEFAULT_STYLE.motion,
        duration: 220,
        easing: 'sharp',
        motif: 'scanline',
        scrollIntensity: 0.52,
      },
      texture: {
        ...DEFAULT_STYLE.texture,
        grain: 0.03,
        imageSaturation: 0.95,
        imageContrast: 1.08,
        imageBrightness: 1,
      },
      light: { ...DEFAULT_STYLE.light, shadowDepth: 0.18, shadowSoftness: 0.42, highlight: 0.18 },
      depth: { ...DEFAULT_STYLE.depth, glass: 0.18, parallax: 0.1 },
      mood: ['cold', 'sharp', 'minimal'],
      anchors: [
        {
          id: 'anchor-cold-modern-interface',
          type: 'site',
          title: 'Structured modern interface',
          url: '',
          note: 'Cool palette, crisp edges, denser rhythm, quick motion.',
          weight: 0.68,
        },
      ],
    },
  },
  darkAcademic: {
    label: { zh: '极夜', en: 'Dark academic' },
    description: { zh: '深色、书卷、低亮度高对比', en: 'dark, literary, high contrast' },
    style: {
      ...DEFAULT_STYLE,
      preset: 'darkAcademic',
      color: {
        ...DEFAULT_STYLE.color,
        background: '#11100d',
        surface: '#1d1913',
        text: '#f1e8d2',
        muted: '#a99d83',
        primary: '#c08b49',
        secondary: '#6f8f72',
        contrast: 0.86,
        saturation: 0.42,
        temperature: 0.3,
      },
      design: {
        ...DEFAULT_STYLE.design,
        spacing: 0.58,
        alignment: 'editorial',
        hierarchy: 0.8,
        contrast: 0.82,
        proportion: 0.54,
      },
      typography: {
        ...DEFAULT_STYLE.typography,
        personality: 'literary',
        display: 'serif',
        body: 'serif',
        tracking: 3,
      },
      space: { ...DEFAULT_STYLE.space, density: 0.42, radius: 4, sectionGap: 104 },
      motion: {
        ...DEFAULT_STYLE.motion,
        mode: 'calm',
        duration: 360,
        motif: 'film',
        scrollIntensity: 0.28,
      },
      texture: {
        ...DEFAULT_STYLE.texture,
        grain: 0.14,
        imageSaturation: 0.85,
        imageContrast: 1.12,
        imageBrightness: 0.92,
      },
      light: { ...DEFAULT_STYLE.light, shadowDepth: 0.65, shadowSoftness: 0.7, highlight: 0.1 },
      depth: { ...DEFAULT_STYLE.depth, blur: 2, glass: 0.18, parallax: 0.18 },
      mood: ['literary', 'moody', 'deep'],
      anchors: [
        {
          id: 'anchor-dark-library',
          type: 'image',
          title: 'Low-lit library table',
          url: '',
          note: 'Dark surface, warm text, long soft shadows, bookish contrast.',
          weight: 0.78,
        },
      ],
    },
  },
  journal: {
    label: { zh: '手记', en: 'Journal' },
    description: { zh: '亲密、手写感、温柔页面节奏', en: 'personal, warm, notebook-like' },
    style: {
      ...DEFAULT_STYLE,
      preset: 'journal',
      color: {
        ...DEFAULT_STYLE.color,
        background: '#f2e5cf',
        surface: '#e8d4b7',
        text: '#2c2016',
        muted: '#755f49',
        primary: '#a65f3d',
        secondary: '#65805a',
        saturation: 0.48,
        temperature: 0.55,
      },
      design: {
        ...DEFAULT_STYLE.design,
        spacing: 0.64,
        alignment: 'loose',
        hierarchy: 0.58,
        contrast: 0.52,
        proportion: 0.38,
      },
      typography: {
        ...DEFAULT_STYLE.typography,
        personality: 'journal',
        display: 'serif',
        body: 'sans',
        tracking: 1,
      },
      space: { ...DEFAULT_STYLE.space, density: 0.38, radius: 12, sectionGap: 106 },
      motion: {
        ...DEFAULT_STYLE.motion,
        mode: 'calm',
        duration: 340,
        motif: 'botanical',
        scrollIntensity: 0.3,
      },
      texture: {
        ...DEFAULT_STYLE.texture,
        grain: 0.13,
        imageSaturation: 0.95,
        imageContrast: 0.95,
        imageBrightness: 1.03,
      },
      light: { ...DEFAULT_STYLE.light, shadowDepth: 0.24, shadowSoftness: 0.75, highlight: 0.15 },
      depth: { ...DEFAULT_STYLE.depth, glass: 0.06, parallax: 0.1 },
      mood: ['personal', 'warm', 'handmade'],
      anchors: [
        {
          id: 'anchor-warm-notebook',
          type: 'object',
          title: 'Warm notebook margin',
          url: '',
          note: 'Loose radius, tactile paper, intimate spacing, handwritten warmth.',
          weight: 0.7,
        },
      ],
    },
  },
  film: {
    label: { zh: '胶卷', en: 'Film grain' },
    description: { zh: '暗房、颗粒、暖色影像感', en: 'grainy, cinematic, warm' },
    style: {
      ...DEFAULT_STYLE,
      preset: 'film',
      color: {
        ...DEFAULT_STYLE.color,
        background: '#211b16',
        surface: '#31271e',
        text: '#f5e6c8',
        muted: '#bd9f77',
        primary: '#d0733f',
        secondary: '#6e8a74',
        contrast: 0.78,
        saturation: 0.58,
        temperature: 0.62,
      },
      design: {
        ...DEFAULT_STYLE.design,
        spacing: 0.5,
        alignment: 'offset',
        hierarchy: 0.72,
        contrast: 0.74,
        proportion: 0.76,
      },
      typography: {
        ...DEFAULT_STYLE.typography,
        personality: 'cinematic',
        display: 'serif',
        body: 'sans',
        tracking: 8,
      },
      space: { ...DEFAULT_STYLE.space, density: 0.48, radius: 8, sectionGap: 92 },
      motion: {
        ...DEFAULT_STYLE.motion,
        duration: 320,
        easing: 'easeInOut',
        motif: 'film',
        scrollIntensity: 0.58,
      },
      texture: {
        ...DEFAULT_STYLE.texture,
        grain: 0.18,
        imageSaturation: 1.08,
        imageContrast: 1.12,
        imageBrightness: 0.96,
      },
      light: { ...DEFAULT_STYLE.light, shadowDepth: 0.5, shadowSoftness: 0.62, highlight: 0.12 },
      depth: { ...DEFAULT_STYLE.depth, blur: 1, glass: 0.14, parallax: 0.2 },
      mood: ['cinematic', 'grainy', 'warm'],
      anchors: [
        {
          id: 'anchor-film-still',
          type: 'film',
          title: 'Warm night film still',
          url: '',
          note: 'Amber highlights, heavy grain, soft blur, slower cinematic rhythm.',
          weight: 0.82,
        },
      ],
    },
  },
  y2k: {
    label: { zh: 'Y2K', en: 'Y2K' },
    description: { zh: '高饱和、数码感、强反馈', en: 'vivid, digital, punchy' },
    style: {
      ...DEFAULT_STYLE,
      preset: 'y2k',
      color: {
        ...DEFAULT_STYLE.color,
        background: '#eef6ff',
        surface: '#d8e4ff',
        text: '#140f2d',
        muted: '#5b4a95',
        primary: '#7c3aed',
        secondary: '#06b6d4',
        contrast: 0.9,
        saturation: 0.82,
        temperature: -0.15,
      },
      design: {
        ...DEFAULT_STYLE.design,
        spacing: 0.36,
        alignment: 'grid',
        hierarchy: 0.86,
        contrast: 0.9,
        proportion: 0.68,
      },
      typography: {
        ...DEFAULT_STYLE.typography,
        personality: 'digital',
        display: 'sans',
        body: 'sans',
        tracking: 12,
      },
      space: { ...DEFAULT_STYLE.space, density: 0.58, radius: 16, sectionGap: 82 },
      motion: {
        ...DEFAULT_STYLE.motion,
        mode: 'lively',
        duration: 180,
        easing: 'sharp',
        motif: 'scanline',
        scrollIntensity: 0.72,
      },
      texture: {
        ...DEFAULT_STYLE.texture,
        grain: 0.02,
        imageSaturation: 1.22,
        imageContrast: 1.14,
        imageBrightness: 1.04,
      },
      light: { ...DEFAULT_STYLE.light, shadowDepth: 0.3, shadowSoftness: 0.34, highlight: 0.28 },
      depth: { ...DEFAULT_STYLE.depth, blur: 3, glass: 0.32, parallax: 0.24 },
      mood: ['digital', 'playful', 'sharp'],
      anchors: [
        {
          id: 'anchor-y2k-screen',
          type: 'image',
          title: 'Glossy early-web screen',
          url: '',
          note: 'High saturation, glassy blur, bright contrast, snappy movement.',
          weight: 0.76,
        },
      ],
    },
  },
  minimalPortfolio: {
    label: { zh: '极简作品集', en: 'Minimal portfolio' },
    description: {
      zh: '少量模块、强作品、清晰留白',
      en: 'fewer modules, stronger work, clear space',
    },
    style: {
      ...DEFAULT_STYLE,
      preset: 'minimalPortfolio',
      layout: { landing: 'minimal' },
      color: {
        ...DEFAULT_STYLE.color,
        background: '#f4f3ef',
        surface: '#e7e5df',
        text: '#161616',
        muted: '#595957',
        primary: '#d64f2f',
        secondary: '#286c62',
        contrast: 0.86,
        saturation: 0.42,
        temperature: 0.02,
      },
      design: {
        ...DEFAULT_STYLE.design,
        spacing: 0.72,
        alignment: 'grid',
        hierarchy: 0.84,
        contrast: 0.78,
        proportion: 0.72,
      },
      typography: {
        ...DEFAULT_STYLE.typography,
        personality: 'modern',
        display: 'sans',
        body: 'sans',
        scale: 1.42,
        tracking: -4,
      },
      space: { ...DEFAULT_STYLE.space, density: 0.28, radius: 2, sectionGap: 124, cardGap: 24 },
      motion: {
        ...DEFAULT_STYLE.motion,
        duration: 220,
        easing: 'sharp',
        motif: 'none',
        ambient: false,
        scrollIntensity: 0.18,
      },
      texture: { ...DEFAULT_STYLE.texture, grain: 0.02, imageSaturation: 0.86 },
      light: { ...DEFAULT_STYLE.light, shadowDepth: 0.08, shadowSoftness: 0.48 },
      depth: { ...DEFAULT_STYLE.depth, blur: 0, glass: 0.02, parallax: 0.05 },
      mood: ['minimal', 'sharp', 'quiet'],
    },
  },
  personalJournal: {
    label: { zh: '个人博客', en: 'Personal journal' },
    description: {
      zh: '阅读感、亲密叙事、持续更新',
      en: 'readable, intimate, made for ongoing notes',
    },
    style: {
      ...DEFAULT_STYLE,
      preset: 'personalJournal',
      layout: { landing: 'journal' },
      color: {
        ...DEFAULT_STYLE.color,
        background: '#eee5d2',
        surface: '#ddd0b8',
        text: '#211c16',
        muted: '#665a4b',
        primary: '#a94f38',
        secondary: '#53705b',
        contrast: 0.7,
        saturation: 0.4,
        temperature: 0.38,
      },
      design: {
        ...DEFAULT_STYLE.design,
        spacing: 0.8,
        alignment: 'loose',
        hierarchy: 0.55,
        contrast: 0.52,
        proportion: 0.4,
      },
      typography: {
        ...DEFAULT_STYLE.typography,
        personality: 'journal',
        display: 'serif',
        body: 'serif',
        scale: 1.3,
        tracking: 1,
      },
      space: { ...DEFAULT_STYLE.space, density: 0.24, radius: 8, sectionGap: 126, cardGap: 28 },
      motion: {
        ...DEFAULT_STYLE.motion,
        mode: 'calm',
        duration: 420,
        easing: 'easeInOut',
        motif: 'botanical',
        scrollIntensity: 0.3,
      },
      texture: { ...DEFAULT_STYLE.texture, grain: 0.14, imageSaturation: 0.82 },
      light: { ...DEFAULT_STYLE.light, shadowDepth: 0.16, shadowSoftness: 0.82 },
      depth: { ...DEFAULT_STYLE.depth, blur: 0, glass: 0.02, parallax: 0.06 },
      mood: ['personal', 'literary', 'warm'],
    },
  },
  gradientStudio: {
    label: { zh: '渐变工作室', en: 'Gradient studio' },
    description: {
      zh: '实验色彩、重点项目、数字质感',
      en: 'chromatic, project-led, digitally expressive',
    },
    style: {
      ...DEFAULT_STYLE,
      preset: 'gradientStudio',
      layout: { landing: 'gradient' },
      color: {
        ...DEFAULT_STYLE.color,
        background: '#11131a',
        surface: '#1d2030',
        text: '#f8f5ef',
        muted: '#b8bfd1',
        primary: '#ff5c8a',
        secondary: '#62e6c6',
        contrast: 0.92,
        saturation: 0.88,
        temperature: -0.12,
      },
      design: {
        ...DEFAULT_STYLE.design,
        spacing: 0.4,
        alignment: 'offset',
        hierarchy: 0.9,
        contrast: 0.9,
        proportion: 0.82,
      },
      typography: {
        ...DEFAULT_STYLE.typography,
        personality: 'digital',
        display: 'sans',
        body: 'sans',
        scale: 1.5,
        tracking: -8,
      },
      space: { ...DEFAULT_STYLE.space, density: 0.52, radius: 18, sectionGap: 88, cardGap: 18 },
      motion: {
        ...DEFAULT_STYLE.motion,
        mode: 'lively',
        duration: 190,
        easing: 'sharp',
        motif: 'web',
        scrollIntensity: 0.78,
      },
      texture: {
        ...DEFAULT_STYLE.texture,
        grain: 0.04,
        imageSaturation: 1.16,
        imageContrast: 1.08,
      },
      light: { ...DEFAULT_STYLE.light, shadowDepth: 0.48, shadowSoftness: 0.58, highlight: 0.34 },
      depth: { ...DEFAULT_STYLE.depth, blur: 4, glass: 0.38, parallax: 0.28 },
      mood: ['digital', 'playful', 'sharp'],
    },
  },
  organic: {
    label: { zh: '自然系', en: 'Organic' },
    description: { zh: '草木、松弛、低刺激色彩', en: 'earthy, loose, low-stimulus' },
    style: {
      ...DEFAULT_STYLE,
      preset: 'organic',
      color: {
        ...DEFAULT_STYLE.color,
        background: '#e8e1cd',
        surface: '#d8cfb6',
        text: '#1f2117',
        muted: '#667057',
        primary: '#587246',
        secondary: '#b08b42',
        saturation: 0.36,
        temperature: 0.22,
      },
      design: {
        ...DEFAULT_STYLE.design,
        spacing: 0.78,
        alignment: 'loose',
        hierarchy: 0.44,
        contrast: 0.48,
        proportion: 0.42,
      },
      typography: {
        ...DEFAULT_STYLE.typography,
        personality: 'organic',
        display: 'serif',
        body: 'sans',
        tracking: 0,
      },
      space: { ...DEFAULT_STYLE.space, density: 0.3, radius: 14, sectionGap: 118 },
      motion: {
        ...DEFAULT_STYLE.motion,
        mode: 'calm',
        duration: 460,
        easing: 'easeInOut',
        motif: 'botanical',
        scrollIntensity: 0.4,
      },
      texture: {
        ...DEFAULT_STYLE.texture,
        grain: 0.1,
        imageSaturation: 0.88,
        imageContrast: 0.94,
        imageBrightness: 1.02,
      },
      light: { ...DEFAULT_STYLE.light, shadowDepth: 0.18, shadowSoftness: 0.8, highlight: 0.12 },
      depth: { ...DEFAULT_STYLE.depth, glass: 0.04, parallax: 0.08 },
      mood: ['organic', 'quiet', 'earthy'],
      anchors: [
        {
          id: 'anchor-organic-paper',
          type: 'object',
          title: 'Pressed leaf and rough paper',
          url: '',
          note: 'Earthy color, relaxed gaps, soft texture, low-stimulus motion.',
          weight: 0.74,
        },
      ],
    },
  },
}
